package Front.Mejores;

import Logic.Pelicula;
import Logic.Interaccion;
import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author JEREMY
 */
public class JPMejores extends javax.swing.JPanel {

    Interaccion atributos = new Interaccion();
    private String selectTabla = "pelicula";
    private String SQL;
    private Pelicula pelicula;
    
    public JPMejores() {
        initComponents();
        jTableTablaEstudiantes.getTableHeader().setBackground(new Color(127, 0, 0));
        jTableTablaEstudiantes.getTableHeader().setFont(new Font("Segoe UI Symbol", Font.BOLD, 12));
        jTableTablaEstudiantes.getTableHeader().setForeground(Color.WHITE);
        this.SQL = "select * from pelicula";
        llenarTabla();
        
    }
    
    private void llenarTabla(){
        ArrayList<Pelicula> listaPeliculas = atributos.busquedaArray(selectTabla, SQL);
        Collections.sort(listaPeliculas);
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Código", "Nombre", "Estreno", "Idioma", "Puntaje","Sipnosis", "Genero", "Director"}, 10);
        jTableTablaEstudiantes.setModel(modelo);
        
        TableModel modeloDatos = jTableTablaEstudiantes.getModel();
        for(int i = 0; i < 10 ; i ++){
            pelicula = listaPeliculas.get(i);
            modeloDatos.setValueAt(pelicula.getIdPelicula(), i, 0);
            modeloDatos.setValueAt(pelicula.getNombrePelicula(), i, 1);
            modeloDatos.setValueAt(pelicula.getEstreno(), i, 2);
            modeloDatos.setValueAt(pelicula.getIdioma(), i, 3);
            modeloDatos.setValueAt(pelicula.getPuntuacionSobre5(), i, 4);
            modeloDatos.setValueAt(pelicula.getSinopsis(), i, 5);
            modeloDatos.setValueAt(pelicula.getGenero(), i, 6);
            modeloDatos.setValueAt(pelicula.getDirector(), i, 7);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTablaEstudiantes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 0, 0)));

        jTableTablaEstudiantes.setAutoCreateRowSorter(true);
        jTableTablaEstudiantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 0, 0)));
        jTableTablaEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTableTablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Estreno", "Idioma", "Puntaje", "Sipnosis", "Genero", "Director"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTablaEstudiantes.setGridColor(new java.awt.Color(127, 0, 0));
        jTableTablaEstudiantes.setSelectionBackground(new java.awt.Color(255, 214, 214));
        jTableTablaEstudiantes.setShowGrid(true);
        jTableTablaEstudiantes.getTableHeader().setResizingAllowed(false);
        jTableTablaEstudiantes.getTableHeader().setReorderingAllowed(false);
        jTableTablaEstudiantes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTableTablaEstudiantesMouseMoved(evt);
            }
        });
        jTableTablaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTablaEstudiantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableTablaEstudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTableTablaEstudiantesMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTablaEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTablaEstudiantesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTablaEstudiantesMouseMoved
    }//GEN-LAST:event_jTableTablaEstudiantesMouseMoved

    private void jTableTablaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTablaEstudiantesMouseClicked
        int fila = jTableTablaEstudiantes.getSelectedRow();
        int colu = jTableTablaEstudiantes.getSelectedColumn();
        if (colu == 5) {
            String titulo=String.valueOf(jTableTablaEstudiantes.getValueAt(fila, 1));
            String sipnosis=String.valueOf(jTableTablaEstudiantes.getValueAt(fila, 5));
        }
    }//GEN-LAST:event_jTableTablaEstudiantesMouseClicked

    private void jTableTablaEstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTablaEstudiantesMouseEntered

    }//GEN-LAST:event_jTableTablaEstudiantesMouseEntered

    private void jTableTablaEstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTablaEstudiantesMouseExited

    }//GEN-LAST:event_jTableTablaEstudiantesMouseExited
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
